name: Create release branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version'
        required: true

jobs:
  create-release-branch:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Publish release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/release/${{ steps.date.outputs.date }}_${{ github.event.inputs.version }}'
          sha: '${{ github.event.pull_request.head.sha }}'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Version
        uses: jaywcjlove/github-action-package@main
        with:
          path: ./package.json
          version: '${{ github.event.inputs.version }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: dev
          token: ${{secrets.PAT}}
          branch: 'release/${{ steps.date.outputs.date }}_${{ github.event.inputs.version }}'
          title: '[Automated]: ${{ github.event.inputs.version }} downmerge'
